# Generated by Django 4.2 on 2023-04-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
