# Generated by Django 4.2 on 2023-04-25 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myblog', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Likes',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
