# Generated by Django 4.2 on 2023-04-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_post_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='image',
        ),
    ]
